export const UI_SA_GET_ITEMS_LIST = 'UI_SA_GET_ITEMS_LIST';
export const SA_RE_SAVE_ITEMS_LIST = 'SA_RE_SAVE_ITEMS_LIST';
export const SA_RE_SAVE_SEARCH_ITEMS_LIST = 'SA_RE_SAVE_SEARCH_ITEMS_LIST';
export const UI_RE_ADD_ITEM = 'UI_RE_ADD_ITEM';
export const UI_RE_RESET_ITEMS_LIST = 'UI_RE_RESET_ITEMS_LIST';
export const UI_RE_EDIT_ITEM = 'UI_RE_EDIT_ITEM';
export const UI_RE_TOGGLE_FAVOURITE_ITEM = 'UI_RE_TOGGLE_FAVOURITE_ITEM';
export const UI_RE_REMOVE_ITEM = 'UI_RE_REMOVE_ITEM';