export const GET_ITEMS_LIST = 'GET_ITEMS_LIST';
export const SA_RE_SAVE_ITEMS_LIST = 'SA_RE_SAVE_ITEMS_LIST';
export const SAVE_SEARCH_ITEMS_LIST = 'SAVE_SEARCH_ITEMS_LIST';
export const ADD_ITEM = 'UI_RE_ADD_ITEM';
export const EDIT_ITEM = 'UI_RE_EDIT_ITEM';
export const REMOVE_ITEM = 'UI_RE_REMOVE_ITEM';
export const RESET_ITEMS_LIST = 'UI_RE_RESET_ITEMS_LIST';

export const GET_ITEMS_LIST_SUCCESS = 'GET_ITEMS_LIST_SUCCESS';
export const GET_ITEMS_LIST_FAIL = 'GET_ITEMS_LIST_FAIL';